/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Balance"
#define F_CLASS_VERSION                         4
#define F_CLASS_REVISION                        0
#define F_CLASS_VERSION_STRING                  "04.00 (2006/08/09)"

#include "Private.h"

#include <feelin/class_startup.c>
