/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Application"
#define F_CLASS_VERSION                         12
#define F_CLASS_REVISION                        0
#define F_CLASS_VERSION_STRING                  "12.00 (2006/06/25)"

#include "Private.h"

#include <feelin/class_startup.c>
