/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Decorator"
#define F_CLASS_VERSION                         1
#define F_CLASS_REVISION                        4
#define F_CLASS_VERSION_STRING                  "01.04 (2005/12/09)"

#include "Private.h"

#include <feelin/class_startup.c>
