/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Element"
#define F_CLASS_VERSION                         2
#define F_CLASS_REVISION                        0
#define F_CLASS_VERSION_STRING                  "02.00 (2007/07/08)"

#include "Private.h"

#include <feelin/class_startup.c>
