/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Slider"
#define F_CLASS_VERSION                         4
#define F_CLASS_REVISION                        2
#define F_CLASS_VERSION_STRING                  "04.02 (2005/12/11)"

#include "Private.h"

#include <feelin/class_startup.c>
