/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Decorator-Flatty"
#define F_CLASS_VERSION                         1
#define F_CLASS_REVISION                        80
#define F_CLASS_VERSION_STRING                  "01.80 (2007/07/19)"

#include "Private.h"

#include <feelin/class_startup.c>
