/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Radio"
#define F_CLASS_VERSION                         2
#define F_CLASS_REVISION                        10
#define F_CLASS_VERSION_STRING                  "02.10 (2006/02/20)"

#include "Private.h"

#include <feelin/class_startup.c>
