/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "XMLObject"
#define F_CLASS_VERSION                         5
#define F_CLASS_REVISION                        0
#define F_CLASS_VERSION_STRING                  "05.00 (2007/07/22)"

#include "Private.h"

#include <feelin/class_startup.c>
