/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Document"
#define F_CLASS_VERSION                         3
#define F_CLASS_REVISION                        0
#define F_CLASS_VERSION_STRING                  "03.00 (2006/02/10)"

#include "Private.h"

#include <feelin/class_startup.c>
