/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Window"
#define F_CLASS_VERSION                         13
#define F_CLASS_REVISION                        0
#define F_CLASS_VERSION_STRING                  "13.00 (2006/05/27)"

#include "Private.h"

#include <feelin/class_startup.c>
