EXTENS = fc

include /Feelin/Sources/_template/makefile.header.os4

objsC := $(patsubst %.c,%.o,  $(wildcard *.c))
#objsH := $(addsuffix .gch,$(wildcard *.h))

all : $(objsC) $(LINKED_LIBS)
	@ $(LINK_LIB) $(LOPT) Project.o $(filter-out Project.o, $(objsC)) -o $(DST)/$(NAME).$(EXTENS) $(ADDLIBS_OS4_GCC) -ldebug -lSASC_func_OS4
	@ echo ">>" [1m$(DST)/$(NAME).$(EXTENS)[0m Version [1m$(VER).$(REV)[0m

clean :
	delete #?.(o|gch)

