EXTENS = fc

include Feelin:Sources/_template/makefile.header.mos

objs := $(patsubst %.c,%.o,$(wildcard *.c))

$(DST)/$(NAME).$(EXTENS) : $(objs)
	@ Avail >NIL: FLUSH
	@ $(LINK) $(LOPT) -o Project.o $(filter-out Project.o, $^) $(DST)/$(NAME).$(EXTENS) -lfeelin_mos -ldebug $(ADDLIBS)
	@ echo ">>" [1m$(DST)/$(NAME).$(EXTENS)[0m Version [1m$(VER).$(REV)[0m

