/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Family"
#define F_CLASS_VERSION                         6
#define F_CLASS_REVISION                        0
#define F_CLASS_VERSION_STRING                  "06.00 (2006/10/19)"

#include "Private.h"

#include <feelin/class_startup.c>
