/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Family"
#define F_CLASS_VERSION                         7
#define F_CLASS_REVISION                        0
#define F_CLASS_VERSION_STRING                  "07.00 (2007/07/23)"

#include "Private.h"

#include <feelin/class_startup.c>
