/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Group"
#define F_CLASS_VERSION                         12
#define F_CLASS_REVISION                        2
#define F_CLASS_VERSION_STRING                  "12.02 (2007/07/25)"

#include "Private.h"

#include <feelin/class_startup.c>
