#
#  Use this makefile to create feelin.library
#

include /Feelin/Sources/_make/makefile-header.68k.gcc

OBJECTS = feelin.o lib_Link.o lib_Memory.o lib_Hash.o lib_Dynamic.o lib_DynamicAuto.o \
	lib_OOS.o lib_Shared.o lib_More.o lib_Atoms.o fc_Class.o fc_Object.o

all : $(OBJECTS)
	@ echo ">>[1mLinking feelin.library[0m"
	@ $(LINKER) $(OBJECTS) -nostartfiles $(LINKER_OUTPUT) /Feelin/libs/feelin.library $(LINKER_OPTIONS) $(LINKER_LIBS)
	@ /C/Avail >NIL: FLUSH

%.o : %.c Private.h
	@ echo ">>"[1m$<[0m
	$(COMPILER) $(COMPILER_OPTIONS) $(COMPILER_OBJECT) $@ $<

