/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Page"
#define F_CLASS_VERSION                         1
#define F_CLASS_REVISION                        0
#define F_CLASS_VERSION_STRING                  "01.00 (2005/12/30)"

#include "Private.h"

#include <feelin/class_startup.c>
