/*
**
**  This file was automatically generated by F_Make from "Project.c"
**
*/

#define F_CLASS_NAME                            "Area"
#define F_CLASS_VERSION                         10
#define F_CLASS_REVISION                        0
#define F_CLASS_VERSION_STRING                  "10.00 (2006/08/10)"

#include "Private.h"

#include <feelin/class_startup.c>
